[2024-06-22T07:43:18.316+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-22T07:43:18.327+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_v2.third_task manual__2024-06-22T07:41:30.190033+00:00 [queued]>
[2024-06-22T07:43:18.332+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_v2.third_task manual__2024-06-22T07:41:30.190033+00:00 [queued]>
[2024-06-22T07:43:18.332+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 7
[2024-06-22T07:43:18.339+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): third_task> on 2024-06-22 07:41:30.190033+00:00
[2024-06-22T07:43:18.341+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2031) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-22T07:43:18.342+0000] {standard_task_runner.py:63} INFO - Started process 2033 to run task
[2024-06-22T07:43:18.343+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v2', 'third_task', 'manual__2024-06-22T07:41:30.190033+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpm1g6eaf3']
[2024-06-22T07:43:18.343+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask third_task
[2024-06-22T07:43:18.366+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag_v2.third_task manual__2024-06-22T07:41:30.190033+00:00 [running]> on host 65f8df8d6172
[2024-06-22T07:43:18.406+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gnosia93' AIRFLOW_CTX_DAG_ID='first_dag_v2' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T07:41:30.190033+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-22T07:41:30.190033+00:00'
[2024-06-22T07:43:18.407+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-22T07:43:18.413+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-22T07:43:18.413+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am third task, .. gnosia93']
[2024-06-22T07:43:18.418+0000] {subprocess.py:86} INFO - Output:
[2024-06-22T07:43:18.419+0000] {subprocess.py:93} INFO - I am third task, .. gnosia93
[2024-06-22T07:43:18.419+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-22T07:43:18.419+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-22T07:43:18.431+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=first_dag_v2, task_id=third_task, run_id=manual__2024-06-22T07:41:30.190033+00:00, execution_date=20240622T074130, start_date=20240622T074318, end_date=20240622T074318
[2024-06-22T07:43:18.440+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-22T07:43:18.449+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-22T07:43:18.450+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
