[2024-06-22T07:41:32.351+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-22T07:41:32.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_v2.third_task manual__2024-06-22T07:41:30.190033+00:00 [queued]>
[2024-06-22T07:41:32.366+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_v2.third_task manual__2024-06-22T07:41:30.190033+00:00 [queued]>
[2024-06-22T07:41:32.367+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-22T07:41:32.374+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): third_task> on 2024-06-22 07:41:30.190033+00:00
[2024-06-22T07:41:32.376+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2003) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-22T07:41:32.377+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v2', 'third_task', 'manual__2024-06-22T07:41:30.190033+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp_9r6zocu']
[2024-06-22T07:41:32.378+0000] {standard_task_runner.py:63} INFO - Started process 2005 to run task
[2024-06-22T07:41:32.378+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask third_task
[2024-06-22T07:41:32.399+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag_v2.third_task manual__2024-06-22T07:41:30.190033+00:00 [running]> on host 65f8df8d6172
[2024-06-22T07:41:32.439+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gnosia93' AIRFLOW_CTX_DAG_ID='first_dag_v2' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T07:41:30.190033+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-22T07:41:30.190033+00:00'
[2024-06-22T07:41:32.440+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-22T07:41:32.448+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-22T07:41:32.449+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am third task, .. gnosia93']
[2024-06-22T07:41:32.453+0000] {subprocess.py:86} INFO - Output:
[2024-06-22T07:41:32.454+0000] {subprocess.py:93} INFO - I am third task, .. gnosia93
[2024-06-22T07:41:32.454+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-22T07:41:32.455+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-22T07:41:32.468+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=first_dag_v2, task_id=third_task, run_id=manual__2024-06-22T07:41:30.190033+00:00, execution_date=20240622T074130, start_date=20240622T074132, end_date=20240622T074132
[2024-06-22T07:41:32.517+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-22T07:41:32.525+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-22T07:41:32.526+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
